# Generated by Django 3.0.2 on 2020-01-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_disqualified', models.BooleanField(verbose_name='black is disqualified')),
                ('white_disqualified', models.BooleanField(verbose_name='white is disqualified')),
                ('black_stalled', models.BooleanField(verbose_name='black has stalled')),
                ('white_stalled', models.BooleanField(verbose_name='white has stalled')),
                ('cubes_on_lower_black', models.PositiveIntegerField(verbose_name="cubes on black's lower goal")),
                ('cubes_on_lower_white', models.PositiveIntegerField(verbose_name="cubes on white's lower goal")),
                ('cubes_on_upper_black', models.PositiveIntegerField(verbose_name="cubes on black's upper goal")),
                ('cubes_on_upper_white', models.PositiveIntegerField(verbose_name="cubes on white's upper goal")),
                ('cubes_on_black_field', models.PositiveIntegerField(verbose_name='cubes on black field')),
                ('cubes_on_white_field', models.PositiveIntegerField(verbose_name='cubes on white field')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NP', 'Not played'), ('PL', 'Playing'), ('SC', 'Scoring'), ('FI', 'Finished')], default='NP', max_length=2)),
                ('black_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_black', to='teams.Team', verbose_name='black team')),
                ('partial_black_score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_as_partial_black', to='matches.Score', verbose_name='partial score for black team')),
                ('partial_white_score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_as_partial_white', to='matches.Score', verbose_name='partial score for white team')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match', to='matches.Score', verbose_name='score')),
                ('white_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_white', to='teams.Team', verbose_name='white team')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
    ]
