# Generated by Django 3.0.2 on 2020-01-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_add_notes_and_adhoc_to_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='partial_black_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='partial_white_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='match',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='matches.Match', verbose_name='match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='black_adhoc',
            field=models.IntegerField(default=0, help_text='Points given by the referres on exceptional or unforseen circumstances', verbose_name='ad-hoc points for black team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='black_disqualified',
            field=models.BooleanField(default=False, verbose_name='black is disqualified'),
        ),
        migrations.AlterField(
            model_name='score',
            name='black_stalled',
            field=models.BooleanField(default=False, verbose_name='black has stalled'),
        ),
        migrations.AlterField(
            model_name='score',
            name='white_adhoc',
            field=models.IntegerField(default=0, help_text='Points given by the referres on exceptional or unforseen circumstances', verbose_name='ad-hoc points for white team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='white_disqualified',
            field=models.BooleanField(default=False, verbose_name='white is disqualified'),
        ),
        migrations.AlterField(
            model_name='score',
            name='white_stalled',
            field=models.BooleanField(default=False, verbose_name='white has stalled'),
        ),
        migrations.CreateModel(
            name='PartialScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disqualified', models.BooleanField(default=False, verbose_name='is disqualified')),
                ('stalled', models.BooleanField(default=False, verbose_name='has stalled')),
                ('cubes_on_lower_goal', models.PositiveIntegerField(verbose_name='cubes on lower goal')),
                ('cubes_on_upper_goal', models.PositiveIntegerField(verbose_name='cubes on upper goal')),
                ('cubes_on_field', models.PositiveIntegerField(verbose_name='cubes on field')),
                ('adhoc', models.IntegerField(default=0, verbose_name='ad-hoc points')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('match_as_black', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_black', to='matches.Match', verbose_name='match as black')),
                ('match_as_white', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_white', to='matches.Match', verbose_name='match as white')),
            ],
            options={
                'verbose_name': 'partial score',
                'verbose_name_plural': 'partial scores',
            },
        ),
    ]
