# Generated by Django 3.0.3 on 2020-02-12 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20200121_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NP', 'Not played'), ('PL', 'Playing'), ('SC', 'Scoring'), ('FI', 'Finished')], default='NP', max_length=2, verbose_name='status'),
        ),
    ]
