# Generated by Django 3.0.3 on 2020-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20200212_2053'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['white_team'], name='matches_mat_white_t_7faa5c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['black_team'], name='matches_mat_black_t_6d8640_idx'),
        ),
    ]
