# Generated by Django 3.0.2 on 2020-01-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='key ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('colour', models.CharField(help_text='HTML colour used to visually identify this category', max_length=20, verbose_name='colour')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='key ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('contact_info', models.TextField(blank=True, verbose_name='contact information')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='key ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.Category', verbose_name='category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.Institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
    ]
