# Generated by Django 3.0.3 on 2020-03-06 21:35

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='raffle',
            field=models.PositiveIntegerField(default=teams.models.gen_raffle_result, verbose_name='raffle result'),
        ),
    ]
