# Generated by Django 3.0.7 on 2020-07-06 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0005_auto_20200308_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('desc', models.CharField(blank=True, default='', help_text='Short description to identify the schedule. Only informative', max_length=80, verbose_name='description')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=None, null=True, verbose_name='round')),
                ('table', models.PositiveIntegerField(default=1, verbose_name='table')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('match', models.ForeignKey(help_text="Related match, or NULL for 'to-be-decided'", null=True, on_delete=django.db.models.deletion.PROTECT, to='matches.Match', verbose_name='match')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'scheduled match',
                'verbose_name_plural': 'scheduled matches',
            },
        ),
        migrations.AddConstraint(
            model_name='scheduledmatch',
            constraint=models.CheckConstraint(check=models.Q(end_time__gte=django.db.models.expressions.F('start_time')), name='coherent_time'),
        ),
        migrations.AddConstraint(
            model_name='scheduledmatch',
            constraint=models.UniqueConstraint(fields=('schedule', 'match'), name='no_match_repetition'),
        ),
    ]
