# Generated by Django 3.0.2 on 2020-01-19 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_add_notes_and_adhoc_to_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(help_text='A short name to help distinguish the schedule', max_length=80, verbose_name='short name')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='round')),
                ('table', models.PositiveIntegerField(default=1, verbose_name='table')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled', to='matches.Match', verbose_name='match')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'scheduled match',
                'verbose_name_plural': 'scheduled matches',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='matches',
            field=models.ManyToManyField(through='schedules.ScheduledMatch', to='matches.Match'),
        ),
    ]
