# Generated by Django 3.0.7 on 2020-07-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20200308_1641'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmatch',
            name='match',
            field=models.ForeignKey(help_text="Related match, or empty for 'to-be-decided'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_on', to='matches.Match', verbose_name='match'),
        ),
        migrations.AlterField(
            model_name='scheduledmatch',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='schedules.Schedule', verbose_name='schedule'),
        ),
    ]
